### ISSUE TITLE
Also facing a class not found error

### ISSUE THREAD

**Issue by DeepSpace2** [dkandalov/code-history-mining#22]
I saw some issues about this from several years back. I'm not sure if there is some sort of regression (using IDEA 2020.1.2) or if I'm doing something wrong.

I've added 

`<intellij path>/plugins/git4idea/lib/git4idea.jar` 

under

`Project Structure -> Platform Settings -> SDKs`

and when importing `git4idea.GitUtil` everything looks fine (including "go to implementation").

However, in run time I'm getting an error:

```
java.lang.ClassNotFoundException: git4idea.GitUtil PluginClassLoader[<my plugin name>, 1.0] com.intellij.ide.plugins.cl.PluginClassLoader@546d8fda
```

(I also have
```
intellij {
    version '2020.1.2'
    plugins = ['Git4Idea']
}
```

in `build.grade` otherwise `import git4idea.GitUtil;` does not work).

**Comment by dkandalov** [comment]
I haven't used or compiled this plugin with the latest IntelliJ for a while so it might not work as intended anymore.

Just to be sure you're trying to do something with code-history-mining plugin right?

**Comment by DeepSpace2** [comment]
Thanks for the reply.

I was trying to use the builtin `git4idea` plugin in my own plugin.
Anyway, I got it working (and realised I may have opened this issue in the wrong place :) ).

For future readers, I got it working by adding `<depends>Git4Idea</depends>` in `plugin.xml`.
